name: my_cupboard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^7.3.0
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  freezed_annotation: ^0.14.3
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  injectable: ^1.4.1
  path:
  path_provider:
  sqflite:
  intl: ^0.17.0


dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  freezed: ^0.14.5
  injectable_generator: ^1.4.1
  json_serializable: ^5.0.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/


 